Haley Holmes - Image Analysis Pipeline Edit
WildMeOrg/old_wildme-docs pull request #18
Opened 2021-01-04 22:43 UTC by haley-holmes

Edits made on 01/04/21 by Haley Holmes. Some paragraph reformatting, small grammar and spelling fixes. finFindR needs a subsection and navigational sidebar link as it is the only program excluded on this page that appears in the ID "ecosystem" diagram (the one with zebras and whales). Unfortunately I have no knowledge on this program and therefore cannot aid in this matter.

2021-01-05 23:57 UTC, TanyaStere42 requested changes
Looks great overall, couple of questions where I just want to confirm it was a deliberate change with an understanding of the language, couple of requests for changes. LOVE the additions to the deepsense description. You added very little, but made it very clear what is going on in terms of retraining, great job!

2021-01-05 23:57 UTC, TanyaStere42 commented on docs/researchers/ia_pipeline.md
> +After detection, one or more ID algorithms are run, looking for similar features between a new anotation and a list of "match against" anotations already in the database. Scores from the query that m
typo: annotation, not anotation

2021-01-05 23:57 UTC, TanyaStere42 commented on docs/researchers/ia_pipeline.md
> +Example Wildbook Species: Giant manta rays, humpback whale flukes, orcas, right whales
why is "Species" capitalized?

2021-01-05 23:57 UTC, TanyaStere42 commented on docs/researchers/ia_pipeline.md
> +PIE Paper Link:https://arxiv.org/pdf/1902.10847.pdf
Why is "Paper Link" capitalized?

2021-01-05 23:57 UTC, TanyaStere42 commented on docs/researchers/ia_pipeline.md
> +Kaggle7 is a deep learning approach to identifying individual humpback whale flukes based on one of the winning entries from a Kaggle competition. Kaggle7 is highly effective at identifying individua
adjust retraining language to match Deepsense language

2021-01-06 18:29 UTC, haley-holmes commented on docs/researchers/ia_pipeline.md
> +Example Wildbook Species: Giant manta rays, humpback whale flukes, orcas, right whales
I capitalized Species for the aesthetic value for the website, if you would like it changed back that's no problem! :)

2021-01-06 18:30 UTC, haley-holmes commented on docs/researchers/ia_pipeline.md
> +PIE Paper Link:https://arxiv.org/pdf/1902.10847.pdf
I also capitalized Paper Link for aesthetic value and can easily be reverted.

2021-01-06 20:35 UTC, TanyaStere42 requested changes
just a typo got missed, the rest looks great

2021-01-06 20:35 UTC, TanyaStere42 commented on docs/researchers/ia_pipeline.md
> +After detection, one or more ID algorithms are run, looking for similar features between a new annotation and a list of "match against" anotations already in the database. Scores from the query that
there's another case of "anotation" instead of "annotation" here

2021-01-06 20:45 UTC, TanyaStere42 approved these changes

2021-01-06 20:45 UTC, merged