Haley Holmes - Researcher Overview Page Edit
WildMeOrg/old_wildme-docs pull request #20
Opened 2021-01-04 22:51 UTC by brmscheiner

Haley Holmes edited this page on 01/03/2021. Mostly wording and grammar edits. Did some minor re-arranging of content in the Introduction and Terminology sections.

2021-01-05 23:49 UTC, TanyaStere42 requested changes
Couple of small changes, but otherwise looks good. Mainly want to make clear that skimmability is the biggest focus in these

2021-01-05 23:49 UTC, TanyaStere42 commented on docs/researchers/researcher_overview.md
> +This introduction covers the most common interactions within the Wildbook platform. It is intended to support Wildbook users and researchers collecting data in the field and to illustrate how to use
Something to look out for (it wasn't consistent before, either) is to reference A Wildbook platform, not THE Wildbook platform. We have a lot of confusion around the distinction between the different platforms and the product, and this is one of the ways we can prevent that

2021-01-05 23:49 UTC, TanyaStere42 commented on docs/researchers/researcher_overview.md
> +In its simplest usage, Wildbook receives a wildlife picture and its related metadata (e.g. where the photo was taken and when), which gets uploaded by a researcher. From here Wildbook uses certain te
> From here Wildbook uses certain terminology to assist users in curating their wildlife data

This is kind of confusing; we don't use the terms to help people, they are incidental to helping people.

2021-01-05 23:49 UTC, TanyaStere42 commented on docs/researchers/researcher_overview.md
> +Because more than one animal appears at the same time in this example MediaAsset, we want to ensure that the relationship between these two Encounters is well understood (i.e. *These two animals were
"also generates" is not technically accurate

2021-01-05 23:49 UTC, TanyaStere42 commented on docs/researchers/researcher_overview.md
> +Under the **Submit** menu, there are two options: **Report an Encounter** and **Bulk Import**. Both options are used to submit data. Report an Encounter can be used by anyone, whereas Bulk Import req
Skimmability has been reduced by putting these together. Is there a way to rework so Report an encounter is discussed completely before Bulk Import? Also can we add links to the related pages?
https://docs.wildme.org/docs/researchers/report_encounter
https://docs.wildme.org/docs/researchers/bulk_import

2021-01-05 23:49 UTC, TanyaStere42 commented on docs/researchers/researcher_overview.md
> +- **Encounter Search** pulls up several filters that can be leveraged to generate a filtered list of all the Encounters the signed-in user has access to. Once the list is generated, additional filter
since calendar per search; should not be plural

2021-01-06 20:05 UTC, haley-holmes commented on docs/researchers/researcher_overview.md
> +In its simplest usage, Wildbook receives a wildlife picture and its related metadata (e.g. where the photo was taken and when), which gets uploaded by a researcher. From here Wildbook uses certain te
Changed to "The following terminology is used by Wildbook programs as users curate their wildlife data" to replace the sentence using the term "assist".

2021-01-06 20:26 UTC, haley-holmes commented on docs/researchers/researcher_overview.md
> +- **Encounter Search** pulls up several filters that can be leveraged to generate a filtered list of all the Encounters the signed-in user has access to. Once the list is generated, additional filter
All fixed!

2021-01-06 20:27 UTC, haley-holmes commented on docs/researchers/researcher_overview.md
> +Under the **Submit** menu, there are two options: **Report an Encounter** and **Bulk Import**. Both options are used to submit data. Report an Encounter can be used by anyone, whereas Bulk Import req
I have re-arranged this section for readability and included the two related webpages. I believe I added them correctly as they worked on my computer, but might be worth a double-check!

2021-01-06 20:27 UTC, haley-holmes commented on docs/researchers/researcher_overview.md
> +Because more than one animal appears at the same time in this example MediaAsset, we want to ensure that the relationship between these two Encounters is well understood (i.e. *These two animals were
Fixed!

2021-01-06 20:35 UTC, haley-holmes commented on docs/researchers/researcher_overview.md
> +This introduction covers the most common interactions within the Wildbook platform. It is intended to support Wildbook users and researchers collecting data in the field and to illustrate how to use
Reviewed the web page to ensure for the correct language.

2021-01-06 20:35 UTC, haley-holmes commented
Implemented Tanya S.'s editing comments on 1/6/21.

2021-01-06 20:36 UTC, TanyaStere42 approved these changes
Wonderful, thank you so much!

2021-01-06 20:36 UTC, merged