added debugging page
WildMeOrg/old_wildme-docs pull request #52
Opened 2022-02-17 17:34 UTC by hwindsor

as requested

2022-02-18 19:45 UTC, brmscheiner requested changes

2022-02-18 19:45 UTC, brmscheiner commented on docs/developers/debugging.md~
> +---
@hwindsor it looks like there was a mistake here. this looks like the contents of `houston.md` were accidentally copied over to `debugging.md~` (notice the tilde). i can easily delete this file - my question is, did you mean to also edit houston.md or is there something that needs to be salvaged here?

2022-02-21 09:53 UTC, hwindsor commented on docs/developers/debugging.md~
> +---
It was an error, removed now. Thanks fgor spotting that

2022-02-22 17:47 UTC, brmscheiner approved these changes

2022-02-22 17:47 UTC, merged