bulk reporting limitation
WildMeOrg/old_wildme-docs pull request #80
Opened 2022-09-28 17:48 UTC by TanyaStere42

a limitation of bulk reporting was identified. I have explained the workaround (and created a general page structure that will be used later)

2022-09-30 21:55 UTC, Atticus29 requested changes

2022-09-30 21:55 UTC, Atticus29 commented on docs/researchers/codex/bulk_reporting.md
> +The majority of custom fields can be entered into the bulk reporting using the method described above. However, there are some limitation. You must fill in any of the following fields during curation
limitations plural.

2022-10-03 18:37 UTC, TanyaStere42 commented on docs/researchers/codex/bulk_reporting.md
> +The majority of custom fields can be entered into the bulk reporting using the method described above. However, there are some limitation. You must fill in any of the following fields during curation
ugh. fixed

2022-10-17 18:15 UTC, Atticus29 approved these changes
LGTM

2022-10-17 18:15 UTC, merged