Update quickstart_firstlogin.md
WildMeOrg/old_wildme-docs pull request #81
Opened 2022-09-30 21:50 UTC by michaelabela

2022-09-30 21:53 UTC, Atticus29 requested changes

2022-09-30 21:53 UTC, Atticus29 commented on docs/researchers/codex/quickstart_firstlogin.md
> +To get set up with an account, use [this link](https://qa.dyn.wildme.io/request) to access Codex’s invitation request page. Alternatively, you may click “Request an invitation” on the Login page or a
This URL takes a user to our QA server. Do we really want that in the quickstart docs?

I think we should be a little more agnostic about which platform the reader is using.

Perhaps something more general like, "navigate to your codex instance's URL, and add /request to the end of the URL")?

2022-09-30 21:54 UTC, michaelabela commented on docs/researchers/codex/quickstart_firstlogin.md
> +To get set up with an account, use [this link](https://qa.dyn.wildme.io/request) to access Codex’s invitation request page. Alternatively, you may click “Request an invitation” on the Login page or a
good catch, yes that definitely makes more sense

2022-09-30 21:55 UTC, TanyaStere42 requested changes
ln 12: these are general documents, not for our QA server specifically, which makes that first sentence misleading (not your fault, directions were unclear). Detail how to navigate from a site home page to the log-in page.
rest looks great

2022-10-03 17:49 UTC, Atticus29 approved these changes
LGTM.

2022-10-05 15:58 UTC, TanyaStere42 approved these changes

2022-10-05 16:01 UTC, merged